export const contact = [
  {
    id: 1,
    name: "Aarav Mehta",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    time: "10:24 AM",
    message: "Hey, what's up?",
    unreadCount: 2,
  },
  {
    id: 2,
    name: "Mansi",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    time: "09:15 AM",
    message: "See you soon!",
  },
  {
    id: 3,
    name: "Karan Patel",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    time: "Yesterday",
    message: "Meeting is confirmed.",
    unreadCount: 1,
  },
  {
    id: 4,
    name: "Neha Joshi",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    time: "12:30 PM",
    message: "Thanks for the help!",
  },
  {
    id: 5,
    name: "Rohan Kumar",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    time: "Today",
    message: "Can we talk now?",
  },
  {
    id: 6,
    name: "Isha Verma",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    time: "Monday",
    message: "Got your message!",
    unreadCount: 3,
  },
  {
    id: 7,
    name: "Vikram Desai",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    time: "1:45 PM",
    message: "Let's catch up soon.",
  },
  {
    id: 8,
    name: "Simran Kaur",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    time: "Today",
    message: "Sure, done!",
  },
  {
    id: 9,
    name: "Arjun Rana",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    time: "Yesterday",
    message: "All set for the event.",
    unreadCount: 1,
  },
  {
    id: 10,
    name: "Ananya Roy",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    time: "10:00 AM",
    message: "Call me when you're free.",
  },
  {
    id: 11,
    name: "Devansh Singh",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    time: "Wednesday",
    message: "Project completed.",
  },
  {
    id: 12,
    name: "Pooja Jain",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    time: "Friday",
    message: "Happy Birthday!",
    unreadCount: 2,
  },
  {
    id: 13,
    name: "Manav Bhatt",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    time: "Yesterday",
    message: "Okay noted.",
  },
  {
    id: 14,
    name: "Kritika Deshmukh",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    time: "Today",
    message: "That sounds fun!",
  },
  {
    id: 15,
    name: "Harsh Vora",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    time: "Tuesday",
    message: "I'll check and update.",
    unreadCount: 4,
  },
];

// Dummy message data for chat
export const dummyMessages = []

